# This Dockerfile requires a pre-build jar-file.
# Run "mvn package" to build one before you execute this build script.

FROM openjdk:14-jdk-slim
COPY ./target/*-shaded.jar /app/application.jar
WORKDIR /app

ENTRYPOINT ["java", "-jar", "/app/application.jar"]