# This Dockerfile requires a pre-build jar-file.
# Run "mvn package" to build one before you execute this build script.

FROM eclipse-temurin:17-jre-alpine
COPY ./target/*-shaded.jar /app/application.jar
WORKDIR /app

ENTRYPOINT ["java", "-jar", "/app/application.jar"]